### ISSUE TITLE
Interfaz 

### ISSUE THREAD

**Issue by d4lion** [xaca/coding_with_friends#4]
Hola 👋 @xaca , espero estes bien, quería consultarte si tienes algún tipo de interfaz pensada para el evento, me gustaría aportar en cualquier aspecto, encantado de conocer tus ideas. Gran propuesta de coding.

**Comment by xaca** [comment]
Buenas noches @d4lion tenemos el sitio www.codingwithfriends.club, este esta configurado con github pages y la idea es que los estudiantes y personas interesadas en los eventos puedan ayudar como voluntarios actualizando la información del sitio y llevando un historial de actividades, por ahora todo lo hacemos con html, css y js. Una configuración de plantilla básica, bienvenido en lo que puedas colaborar, proximamente crearé nuevos issues con temas que requerimos ayuda. Por otro lado interesante tu portafolio, me alegra que alguien tan joven ya tenga un perfil tan completo.
